### ISSUE TITLE
Automatically check "I've played it" when submitting a time vote

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#1056]
Aprops #383, when you submit a time vote, we should automatically check "I've played it."

**Comment by alice-blue** [comment]
If we do this, we should also say we're doing this, so that it's clear that a (potentially) public action will happen as a result of the anonymous vote. (Maybe it should be in the "tips"?)

**Comment by salty-horse** [comment]
I prefer that opposite: NOT showing the time vote input if "played it" is unchecked. It takes too much space on the page.

Is there a scenario where users would want to fill it without marking "played it"?

**Comment by dfabulich** [comment]
Done in #1152
