### ISSUE TITLE
taggame and gametags API accept parameters in different formats

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#1072]
taggame and gametags now accept JSON, but in wildly different ways.

* `gametags` accept parameters either POSTed as `application/x-www-form-urlencoded` data, or in GET parameters (which will be logged 😬)
* `taggame` only accepts parameters POSTed as `application/json`

I think it's confusing to do both.

I think it's natural for `taggame` to use JSON documents (so that we can POST an array, instead of `t0` `t1` `t2` parameters as the old XML API required), so `gametags` should probably do the same thing.

**Comment by dfabulich** [comment]
@salty-horse WDYT?

**Comment by dfabulich** [comment]
I just filed #1081 that we should maybe have a `mytags` API.

It seems to me that `gametags` is kinda doing too much. On the one hand, you can call it with GET parameters <http://localhost:8080/gametags?id=aearuuxv83plclpl&json> and get a convenient source of public data.

But if you want to do a `mine_only` query, you really ought _not_ pass in GET parameters; you should use POST or [QUERY](https://httpwg.org/http-extensions/draft-ietf-httpbis-safe-method-w-body.html) parameters only, so your password won't get logged.

If `viewgame` returns public tags #1078, then maybe we don't need `gametags` at all: you could get the public tags via `viewgame` (GET, naturally) and you can get your personal tags via `mytags` (password required, so POST or QUERY only). 

And then perhaps no one would  ever want to use `gametags`, like, ever again!

**Comment by salty-horse** [comment]
I agree that the current API is bad, and that passwords shouldn't be part of the URL.

Headers are also an option.

**Comment by dfabulich** [comment]
We deprecated `gametags` instead.
