### ISSUE TITLE
Spoiler tags and tag editor tags in dark mode are hard to read

### ISSUE THREAD

**Issue by salty-horse** [iftechfoundation/ifdb#1090]
The light purple text is not legible over the white background. There needs to be more contrast. I think the background should be dark, and the text should be light, but just enough to differentiate from the regular background.

![spoiler](https://github.com/user-attachments/assets/1aa4f9c0-757f-4c32-aa9a-0317cc0d0355)

Tags in the tag editor are also hard to read:
![tag_editor](https://github.com/user-attachments/assets/48624dd1-c190-4133-9294-6c7fec24d54c)

Delete tags dialog: ("X" image has a visible horizontal white line)
![delete_tags](https://github.com/user-attachments/assets/5646648b-d1dd-4736-8236-57c494d47cba)

**Comment by alice-blue** [comment]
I'm pretty sure I fixed the tag editor tag color on Oct. 6: https://github.com/iftechfoundation/ifdb/pull/356

 I'm not sure what happened in the meantime.

**Comment by dfabulich** [comment]
I did a [`git bisect`](https://git-scm.com/docs/git-bisect) and it turned up 017847b94d69cd9276feaf59570a75030665d196

In that commit, the tag editor changed the `<a>` tags into `<span>` tags, which don't have dark mode styling.

**Comment by salty-horse** [comment]
Sorry! I'll be more careful about checking both modes.

**Comment by dfabulich** [comment]
32d653998040bbb72a700c1728de6fe37273d858 also affected the tag editor header in dark mode
