### ISSUE TITLE
viewgame iFiction API returns tags in a bogus format

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#1092]
https://ifdb.org/viewgame?id=aearuuxv83plclpl&ifiction

```
<tags>
<name>achievements</name>
<tagcnt>1</tagcnt>
<gamecnt>51</gamecnt>
<name>adjustable difficulty</name>
<tagcnt>1</tagcnt>
<gamecnt>21</gamecnt>
<name>alcohol</name>
<tagcnt>1</tagcnt>
<gamecnt>24</gamecnt>
```

Each tag should be wrapped in its own `<tag>` element.

**Comment by salty-horse** [comment]
It's due to a limitation of serialize_xml()'s requirements being different than json's - needs to be wrapped especially with `array_map`ping of `["tag"=>$tag]`. You can check how it's handled elsewhere..
