### ISSUE TITLE
Remove instructions about how to unzip files

### ISSUE THREAD

**Issue by salty-horse** [iftechfoundation/ifdb#1116]
When an External Link leads to a ZIP archive, there's a footnote that explains what ZIP is.

Modern operating systems already include built-in support for opening ZIP archives. I don't think it's helpful to link to http://www.info-zip.org/

**Comment by dfabulich** [comment]
I edited the file format https://ifdb.org/fileformat?id=17 and now it just says "Compressed with ZIP."
