### ISSUE TITLE
Moddate on reviews seems to have gotten automatically changed when converting to UTF-8

### ISSUE THREAD

**Issue by alice-blue** [iftechfoundation/ifdb#1117]
Reviews that had unusual characters are now showing the wrong moddate.

**Comment by salty-horse** [comment]
The reviews table has this trigger:
```
`moddate` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
```

**Comment by dfabulich** [comment]
I'm not sure there's anything we can/should do about this now, but maybe if we did #565 it would mitigate some of the harm.

**Comment by dfabulich** [comment]
Now the reviews list their creation date correctly. They all say "* This review was last edited on November 7, 2024" but I think that's acceptable.
