### ISSUE TITLE
Game search results should have a similar template, whether there's a cover or not

### ISSUE THREAD

**Issue by salty-horse** [iftechfoundation/ifdb#1126]
[This search](https://ifdb.org/search?searchfor=author%3Akhaw&searchgo=Search+Games) yields 3 games, one of them without a cover.

It's confusing that the game without the cover is presented differently, with the year and rating in different positions, and the comma after the game title.

![search](https://github.com/user-attachments/assets/6e4c8661-ef3b-4027-9de6-78dc89771033)

**Comment by alice-blue** [comment]
I wonder if it would help to float the cover art to the right, the way we do on the viewgame page? Then the text would line up on the left regardless of whether the game had cover art.

**Comment by salty-horse** [comment]
I prefer the cover art to be on the left, with a blank space when it doesn't exist.
Unlike game pages, I don't think search results should fill the width of their "column", which is what a float right for the cover would do. (Maybe it's just my personal taste.)

**Comment by salty-horse** [comment]
The same issue exists in lists. [Example](https://ifdb.org/viewlist?id=25x843lprpmy6umo)
(Note the lack of spacing above the user's comment when there is no cover)
![list](https://github.com/user-attachments/assets/ebc76694-fabd-4222-946b-d3611d9d7d2a)
