### ISSUE TITLE
Color of tags when adding them is not contrasted enough (default theme)

### ISSUE THREAD

**Issue by manonamora** [iftechfoundation/ifdb#1157]
With the default theme on dark-mode-preferred browser, the tags are almost not visible when you add them to a page (see screenshot).

![image](https://github.com/user-attachments/assets/4f48e81a-999f-4862-ae0d-8488cafae158)

```
@media (prefers-color-scheme: dark), (prefers-color-scheme: light) {
  #tagEditor, #tagDeletor {
    color: rgb(255, 255, 255);
  }
}
```
is overriden by
```
.cklabel {
  color: rgb(0, 0, 128);
  cursor: pointer;
}
```
(which doesn't have a prefer-color-scheme:dark option)

**Comment by alice-blue** [comment]
I previous did this: https://github.com/iftechfoundation/ifdb/pull/356/commits/6cb3eea15db40bc326d02537e2f13b98439653d0

But maybe it got lost in the migration of the tag editor

**Comment by alice-blue** [comment]
I think https://github.com/iftechfoundation/ifdb/pull/1164 may have fixed this.

**Comment by manonamora** [comment]
Is it live yet? Because it's still the same on my end.

**Comment by dfabulich** [comment]
It is live. I tried logging in as you, and it seemed fixed. But there could be a caching issue. 🤔 Try switching browsers just to confirm?

**Comment by manonamora** [comment]
yup that did it. Thanks
