### ISSUE TITLE
Cloudflare broke IP logging

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#1181]
I just logged in from IP address 73.189.95.71 but we tracked the login as coming from 162.158.154.154 (Cloudflare).

**Comment by salty-horse** [comment]
Is there an [`X-Forwarded-For`](https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#x-forwarded-for) header?

**Comment by dfabulich** [comment]
I followed the guide here and now IP logging seems to be working correctly. https://developers.cloudflare.com/support/troubleshooting/restoring-visitor-ips/restoring-original-visitor-ips/
