### ISSUE TITLE
"Too many connections" in error log

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#1202]
```
dfabulich@sack:~$ sudo grep "Too many conn" /var/log/apache2/error.log | head -1
[Mon Dec 09 16:44:24.693076 2024] [php7:warn] [pid 1125171:tid 1125171] [client 154.47.20.215:0] PHP Warning:  mysqli_connect(): (08004/1040): Too many connections in /var/www/html/dbconnect.php on line 76
dfabulich@sack:~$ sudo grep "Too many conn" /var/log/apache2/error.log | wc -l
838
```

When this happens, the site throws a 500 error whatever page happens to cause it (usually `viewgame`).

**Comment by salty-horse** [comment]
Is it just a matter of increasing connections in mysql, or are there code changes needed (like connection pooling?)

**Comment by dfabulich** [comment]
The slow query log showed 2700 instances of #1203, which is now fixed. I'll keep an eye on this for the next week, but I think we're probably out of the woods.

**Comment by dfabulich** [comment]
This hasn't reproduced all week. I think we're in the clear.
