### ISSUE TITLE
Some search parameters need Sort by Relevance functionality

### ISSUE THREAD

**Issue by lkcampbell** [iftechfoundation/ifdb#125]
When a user searches without typing in a search term (i.e. empty search), we do not include Sort by Relevance functionality because there is no concept of relevance in that scenario.

When a user searches using only search parameters, and no search term, Sort by Relevance functionality may or may not needed, depending on which search parameters are being used.

For example, per https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/168, it makes sense to sort the search results of `author:Clive Wilson` by relevance. On the other hand it does not make sense to sort the results of `downloadable:yes` by relevance.

Here is the list of search parameters I think need Sort by Relevance functionality:

- author
- tag
- series
- genre
- forgiveness
- language (maybe? is a single language more "relevant" than one language in a list of other languages?)
- system

Note that this issue does not address *how* relevance is measured for each of these parameters, it only adds the functionality back in for each of these parameters. How the Sort by Relevance works can be figured out later on a case by case basis.

**Comment by lkcampbell** [comment]
@dfabulich, when you get a moment, can you review this list and see if it needs to be changed in anyway? Thanks.

**Comment by dfabulich** [comment]
It's not obvious to me that any of these need "sort by relevance" in the drop down.

https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/168 is a real, serious issue, but I'd propose to fix it by requiring an exact string match with "clive wilson", excluding all of Caleb's games. At that point, relevance indeed makes no sense.

I could separately imagine some "did you mean?" suggestions to handle misspellings, e.g. `author:Cilve Wilson` might have a results page: "No results were found. Did you mean [author:Clive Wilson](https://ifdb.org/search?searchbar=author%3AClive+Wilson)?"

**Comment by lkcampbell** [comment]
Aren't the scenarios for author name pretty much the same as for game title? When you don't know the exact string? You know the last name but not the first. Misspelling. You know part of the name. Etc.

Yes, I agree we could do a "did you mean?" suggestion, but aren't we already doing something like that under the hood when we sort by relevance?

**Comment by lkcampbell** [comment]
The more I think about it, the more I think maybe Relevance Sorting would be better replaced with "did you mean?" scenarios. It does give the user more control over choosing the exact string they want without the indirect and squishy feel of trying to figure out what "relevance" is.
