### ISSUE TITLE
Tip: Removing pending review of a new user

### ISSUE THREAD

**Issue by Durafen** [iftechfoundation/ifdb#15]
After opening new user it tagged as pending review.
To remove this tag and being able to add a new listing run this query in mysql: 

```
update users set profilestatus = NULL where email='you@example.com';
```

Is there a better way to confirm a new user?
It can be added to the readme in opening new user instructions.

**Comment by dfabulich** [comment]
I think I've fixed this with PR #16. It's now easy to sign in as an administrator to activate, trust, and impersonate a new user.
