### ISSUE TITLE
Downloading games from http sites doesn't work

### ISSUE THREAD

**Issue by juhana** [iftechfoundation/ifdb#170]
Chrome (and possibly other browsers) has started to block http downloads originating from https sites. It leads to game downloads silently failing if the file link starts with http:// instead of https://.

Test case: https://ifdb.org/viewgame?id=j3rwlhuy6j6v79qj (click on the "from the author's site" download links)

I don't have a good suggestion how to fix it, links can't be automatically converted to https:// because all servers don't have it set up, for example the test case above. Maybe a warning message if someone tries to add a http download link?

**Comment by juhana** [comment]
...and now I see that it's already been discussed here: https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/1
Although IFArchive links have been fixed, other links are still an issue.

**Comment by erkyrath** [comment]
I suppose we could do a one-time survey of http:// download links, check whether https:// returns the same file, and update if possible. This would be an easy script to write. (To run by hand, I mean. Not as part of the IFDB codebase.)

I don't remember how big the download link list is.
