### ISSUE TITLE
A way to shadowban games

### ISSUE THREAD

**Issue by brirush84** [iftechfoundation/ifdb#30]
I have an idea on how to accomplish this. In patch-schema, we currently have this:

```
--
-- Final view structure for view `gameRatingsSandbox0`
--

/*!50001 DROP TABLE IF EXISTS `gameRatingsSandbox0`*/;
/*!50001 DROP VIEW IF EXISTS `gameRatingsSandbox0`*/;
/*!50001 SET @saved_cs_client          = @@character_set_client */;
/*!50001 SET @saved_cs_results         = @@character_set_results */;
/*!50001 SET @saved_col_connection     = @@collation_connection */;
/*!50001 SET character_set_client      = utf8 */;
/*!50001 SET character_set_results     = utf8 */;
/*!50001 SET collation_connection      = utf8_general_ci */;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50001 VIEW `gameRatingsSandbox0` AS select `reviews`.`gameid` AS `gameid`,avg(if((ifnull(`reviews`.`RFlags`,0) & 2),NULL,`reviews`.`rating`)) AS `avgRating`,std(if((`reviews`.`RFlags` & 2),NULL,`reviews`.`rating`)) AS `stdDevRating`,count(if((`reviews`.`RFlags` & 2),NULL,`reviews`.`rating`)) AS `numRatingsInAvg`,count(`reviews`.`rating`) AS `numRatingsTotal`,count(if(isnull(`reviews`.`special`),`reviews`.`review`,NULL)) AS `numMemberReviews` from (`reviews` left join `users` on((`users`.`id` = `reviews`.`userid`))) where (ifnull((now() > `reviews`.`embargodate`),1) and (`users`.`Sandbox` in (2,3))) group by `reviews`.`gameid` */;
/*!50001 SET character_set_client      = @saved_cs_client */;
/*!50001 SET character_set_results     = @saved_cs_results */;
/*!50001 SET collation_connection      = @saved_col_connection */;

--
-- Final view structure for view `gameRatingsSandbox01`
--

/*!50001 DROP TABLE IF EXISTS `gameRatingsSandbox01`*/;
/*!50001 DROP VIEW IF EXISTS `gameRatingsSandbox01`*/;
/*!50001 SET @saved_cs_client          = @@character_set_client */;
/*!50001 SET @saved_cs_results         = @@character_set_results */;
/*!50001 SET @saved_col_connection     = @@collation_connection */;
/*!50001 SET character_set_client      = utf8 */;
/*!50001 SET character_set_results     = utf8 */;
/*!50001 SET collation_connection      = utf8_general_ci */;
/*!50001 CREATE ALGORITHM=UNDEFINED */
/*!50001 VIEW `gameRatingsSandbox01` AS select `reviews`.`gameid` AS `gameid`,avg(if((ifnull(`reviews`.`RFlags`,0) & 2),NULL,`reviews`.`rating`)) AS `avgRating`,std(if((ifnull(`reviews`.`RFlags`,0) & 2),NULL,`reviews`.`rating`)) AS `stdDevRating`,count(if((ifnull(`reviews`.`RFlags`,0) & 2),NULL,`reviews`.`rating`)) AS `numRatingsInAvg`,count(`reviews`.`rating`) AS `numRatingsTotal`,count(if(isnull(`reviews`.`special`),`reviews`.`review`,NULL)) AS `numMemberReviews` from (`reviews` left join `users` on((`users`.`id` = `reviews`.`userid`))) where (ifnull((now() > `reviews`.`embargodate`),1) and (`users`.`Sandbox` in (0,1))) group by `reviews`.`gameid` */;
/*!50001 SET character_set_client      = @saved_cs_client */;
/*!50001 SET character_set_results     = @saved_cs_results */;
/*!50001 SET collation_connection      = @saved_col_connection */;
```

If we just add an attribute for gameid (like gameid.sandbox), we can put games into sandboxes just like the users, and only show troll sandbox game ratings to troll sandbox people.

This would mean that the games appear in the database but only as having 0 ratings, 0 reviews, etc. We could improve this later on (by adding a message), but for now this would be an easy first step.

I would submit a pull request, but I don't know how to add a new attribute to a preexisting SQL database.

**Comment by dfabulich** [comment]
To be clear, `gameRatingsSandbox0` and `gameRatingsSandbox01` are views, not tables. They're basically just fancy `select` statements, encased in amber.

I haven't thought about this very hard yet, but it seems like you'd add a `sandbox` column to the `games` table, then update the views to match.

For an initial PR, I think it would work to add an `alter table` statement to [patch-schema.sql](https://github.com/iftechfoundation/ifdb/blob/main/sql/patch-schema.sql). You can see other examples there that add columns, though in those cases, they're just adding in columns to the local dev environment.

You could then also drop and recreate the view right there in `patch-schema.sql` as well, just copying and pasting the view definition and changing it there.

To test it, you'll need to `docker-compose down` to tear down the database, then `docker-compose up` to rebuild the DB.

Give it a whirl!

**Comment by dfabulich** [comment]
I should add: ultimately what we'd do is to run the `alter table` statement directly on the production database, adding the column in permanently, then re-export the modified schema to ifarchive. Then, we'd update the code to download the newer `ifarchive` export and delete the schema changes from `patch-schema` in a single commit.

**Comment by brirush84** [comment]
So I submitted a pull request for creating the sandbox attribute for games and for checking it. I found a way to make all sandboxed games display no reviews and no ratings on the game page itself, but I'm having trouble with search. Right now, search finds games with this code in searchutil.php:
```

        $tableList = "games
                      left outer join reviews
                        on reviews.gameid = games.id
                          and ifnull(now() >= reviews.embargodate, 1)
                      left outer join users as reviewuser
                        on reviewuser.id = reviews.userid";

```
I thought I could just add in a line like this:

```
        $tableList = "games
                      left outer join reviews
                        on reviews.gameid = games.id
                          and ifnull(now() >= reviews.embargodate, 1)
				and ifnull(games.sandbox,0) in $sandbox
                      left outer join users as reviewuser
                        on reviewuser.id = reviews.userid";


```
but it causes errors. The virtualization is killing my weak laptop, so I'm going to stop, and probably won't have any time to work on this until next weekend.

**Comment by dfabulich** [comment]
Now that we have a way to bury games (PR #43) do we think we also/still want the ability to shadowban games?

My feeling is no. If a troll creates a game, it's either a fake game, in which case we should delete the listing, or it's a real game, in which case it probably deserves _some_ kinda IFDB entry (possibly a buried one).

**Comment by brirush84** [comment]
Yeah, closing this as a result of #43 sounds great.
