### ISSUE TITLE
Links to "series:"/"genre:"/"system:" searches break special characters

### ISSUE THREAD

**Issue by Keltena** [iftechfoundation/ifdb#305]
When I click the name of a series, genre, or development system that contains certain special characters, I get a broken search where those characters are replaced with mojibake.

For example:
- _[Coke Is It!](https://ifdb.org/viewgame?id=igcp4nw7md3ylwjs)_: clicking genre `Children’s` searches for `genre:ChildrenÂ’s`
- _[Royal Affairs](https://ifdb.org/viewgame?id=efvx6thh6tazqv2o)_: clicking series title `the Crème de la Crème series` searches for `series:the CrÃ¨me de la CrÃ¨me series`
- _[El Espíritu de la Sidra](https://ifdb.org/viewgame?id=l8g79u3ornkvzykl)_: clicking system `Superglús` searches for `system:SuperglÃºs`

The broken versions also appear in the lists on the [Search Tips](https://ifdb.org/search) page.

I'm not sure if any other search parameters have this problem; I know tags and author names don't. It also doesn't occur for all special characters (Chinese and Cyrillic seem fine, for instance).

**Comment by dfabulich** [comment]
Fixed in #1004
