### ISSUE TITLE
Page stretching on mobile

### ISSUE THREAD

**Issue by Keltena** [iftechfoundation/ifdb#312]
When I browse on mobile, the layout is often broken by elements wider than my screen. Some examples, from most to least common:

1. Most fields on the Create/Edit pages, especially External Links:
![The 'New Game Listing' page on mobile. It's more than 3x the width of the mobile layout.](https://github.com/user-attachments/assets/7a16a098-2281-42b4-a408-b5684a0ad2df)
(External Links is an issue even on my laptop, unless I maximize the window.)

2. The Tags table on game pages, which always displays 4 tags per row:
![A game's tags arranged in four columns. The third and fourth columns extend far off the edge of the background.](https://github.com/user-attachments/assets/bb1e5fae-ea26-4d1b-8402-50a5f3dcddd6)

3. Some IFIDs on game pages:
![A 'Game Details' section. The IFIDs extend slightly past the edge of the background.](https://github.com/user-attachments/assets/7998d135-ff64-4764-bbd1-a4ea865f596e)

4. The [My Activity](https://ifdb.org/personal) page layout:
![Page with two columns. The first contains activity like 'Your Reviews'; the second contains two infoboxes ('Quick Stats' and 'Are you an IF author?') that stretch slightly off the page.](https://github.com/user-attachments/assets/ad0e91b7-2e2f-45e3-b0c4-b50ef935ab08)

5. The 'Describe Yourself' field on the [Settings](https://ifdb.org/editprofile) page:
![Screenshot_20240731_095737_Firefox Nightly](https://github.com/user-attachments/assets/d85fd233-5c37-4a4e-8580-54a808156236)

6. Preformatted text:
![A code block from the API documentation page with one long line that stretches the page.](https://github.com/user-attachments/assets/4d7f1ed1-7a9b-4fde-a677-45589746e9fb)

(Screenshots taken in Firefox on Android.)

**Comment by dfabulich** [comment]
1. For historical reasons, we're tracking IFDB bugs in https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues instead of here. (But… maybe we _should_ track them here.)
2. Yeah, mobile support is an after thought on IFDB. I have a PR to improve the game details page, but I got some feedback and never found time to incorporate it, so I still have work to do there. https://github.com/iftechfoundation/ifdb/pull/211
3. I think each of these is a separate bug that would need to be tracked and fixed separately.

**Comment by Keltena** [comment]
Ah, sorry about that. I think I mistakenly assumed that bugs went here and only suggestions went there. I'll remember that for the future.

Would it help if I submitted separate pull requests for each of these (in the right place this time)? Or should I hold off until you find time to get back to that mobile redesign?

**Comment by dfabulich** [comment]
I'm pretty sure my PR addresses the tags issue, specifically.

If you're excited to work now, I don't want to slow you down.

I think what I should do is dust off the old PR, at least enough to resolve its conflicts. Then I'd say you can feel free to file PRs that both merge cleanly (and appear non-broken) into main _and_ merge cleanly into the mobile-redesign branch.

Meanwhile, I'll see if I can get myself to merge the mobile redesign PR sometime this month, at which point, you're clear to file any mobile-friendliness PR you like.

**Comment by dfabulich** [comment]
I've rebased PR #211; give it a spin.

I've filed https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/466 on the editgame page
I've filed https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/467 on the settings page

I actually don't reproduce the My Activity bug, which is to say, I kinda can reproduce it, but not actually on mobile.

IFDB has a `legacy-mobile-styles.css` stylesheet, designed to hide `.rightbar` and `.tipbox` boxes all over the site. The `mobile` CSS activates only when we user-agent sniff and detect iPhone or Android.

https://github.com/iftechfoundation/ifdb/blob/main/www/util.php#L507
https://github.com/iftechfoundation/ifdb/blob/main/www/legacy-mobile-styles.css

As a result, on actual iPhone/Android, the My Activity page hides "Quick Stats" and "Are You an Author?" and the result looks like this. (But in Firefox/Chrome Dev Tools, if you just resize the window to mobile size, the legacy stylesheet won't activate, and you'll get the broken layout you reported.)

<img width=375 src="https://github.com/user-attachments/assets/0fa44f48-fcdc-4fc7-85e9-37783f90b1dc">

**Comment by Keltena** [comment]
> IFDB has a `legacy-mobile-styles.css` stylesheet, designed to hide `.rightbar` and `.tipbox` boxes all over the site. The `mobile` CSS activates only when we user-agent sniff and detect iPhone or Android.
> 
> https://github.com/iftechfoundation/ifdb/blob/main/www/util.php#L507

Ah, that explains why it's not detecting my Android. I just checked my user agent — it starts with `Mozilla/5.0 (Android 14;`, which doesn't match the `Linux; Android` part of that regex.

I'll take a look at your PR next chance I get.
