### ISSUE TITLE
Block tags with preferred synonyms

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#364]
As I write this, we have 139 games tagged "sci-fi" and 670 games tagged "science fiction." We can clean these up, but there's nothing stopping people from adding "sci-fi" back in later.

If somebody tries to add "sci-fi," we should stop them, and suggest adding the tag "science fiction" instead.

**Comment by alice-blue** [comment]
This was completed in https://github.com/iftechfoundation/ifdb/pull/360
