### ISSUE TITLE
Attention: File suggestions to our separate tracker

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#37]
Most new issues should be filed in our [IFDB Suggestion Tracker](https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues).

**If you're unsure whether to file an issue here or there, prefer to file it there.**

Here in this repository, the Issues tab is for bugs in existing functionality, and issues directly related to pull requests.

**Comment by erkyrath** [comment]
(whoops, didn't mean to unpin this)
