### ISSUE TITLE
Can't enter some characters (e.g. emoji) in game titles

### ISSUE THREAD

**Issue by jtn20** [iftechfoundation/ifdb#401]
Attempting to enter emoji into a game title causes the literal entity encoding (`&#xxxxxx;`) to appear instead.
(Maybe some other fields too, haven't checked; but clearly the description doesn't have this trouble. Haven't tried to determine exactly which characters trigger this; maybe those outside the [BMP](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane))?)

For example, the game _[😱🔤😱](https://louphole.itch.io/scream-alphabet-scream)_ is represented on IFDB as _[Scream Alphabet Scream (emojis)](https://ifdb.org/viewgame?id=moq1r96lz5fdq8sf)_. In the edit history you can see me and others flailing around to represent it properly, but whatever I entered, it got converted to `&#128561;&#128292;&#128561;`.

The [IFDB entry](https://ifdb.org/viewgame?id=hnloj99m8u2a43oy) for _[Coca-Cola Presents: 🥤 Fuck Capitalism Jam 2032 🥤](https://princessinternetcafe.itch.io/coca-cola-presents-fuck-capitalism-jam-2032)_ is another example (currently showing the entity encoding).

**Comment by jtn20** [comment]
I happened on [this article](https://adamhooper.medium.com/in-mysql-never-use-utf8-use-utf8mb4-11761243e434), which says that:
* MySQL's `utf8` type can't actually represent the full range of Unicode characters;
* There's no reason not to use `utf8mb4` instead, which can.

I don't know for sure whether IFDB is using the `utf8` type, but a `git grep` through the IFDB source doesn't find any reference to `utf8mb4`. I wonder if this is implicated in this bug.

The characters I already mentioned certainly turn into 4-byte UTF-8 sequences, so by the description in that article, wouldn't be representable in `utf8`.

However, IFDB's problem seems a bit more subtle than just 'code points with a 4-byte UTF-8 representation can't be entered'. I tried characters straddling the 3/4 byte boundary (which is also the BMP boundary), U+FFEE and U+10000, in a game title, and both seemed to work (neither got converted to entities).

**Comment by salty-horse** [comment]
The mysql database is currently using the `latin1` encoding, and any unicode is stored in it using HTML escape sequences. 
(There are places to migrate it: #859 )

This is probably an issue with the functions that convert to/from that HTML representation.

**Comment by salty-horse** [comment]
OK, I see the title is updating just fine, but it's not displaying the HTML codes correctly. I'll fix it.
