### ISSUE TITLE
Rethink or redesign the little icons on the front page

### ISSUE THREAD

**Issue by alice-blue** [iftechfoundation/ifdb#434]
I understand the appeal of having graphics on IFDB, but the little icons on the front page of ifdb are, in my opinion, kind of busy and hard to make out. Could these be replaced with something else, even just a single simple icon that is repeated? Maybe the original icons could be available in one of the custom CSS settings for people who want the nostalgia factor?
![ifdb front page icons](https://github.com/iftechfoundation/ifdb/assets/12779726/454f2775-c71c-4361-9390-217373425d2b)

**Comment by jtn20** [comment]
I think these are gone, as of the big front page redesign?
