### ISSUE TITLE
Remove redundant Links section, move IFWiki link elsewhere

### ISSUE THREAD

**Issue by salty-horse** [iftechfoundation/ifdb#445]
The bottom of game pages has a Links section that is populated with only two items:
* A website, if the game has one.
* A link to IFWiki, if the IFID is found in IFWiki.

The website already appears at the top of the page next to the title and cover art, so it's listed twice.

The link to IFWiki can be placed somewhere else, but where? At the top, next to the website? And it's enough to say "IFWiki page" without mentioning the game's title once again.

I initially looked into it because the two links are rendered on the same line, making them hard to distinguish.
See Anchorhead for an example: https://ifdb.org/viewgame?id=op0uw1gn1tjqmjt7#links-div

**Comment by dfabulich** [comment]
We did this when we did the mobile redesign.
