### ISSUE TITLE
Remove IF Archive Mirror Preferences

### ISSUE THREAD

**Issue by lkcampbell** [iftechfoundation/ifdb#48]
## Repro steps:
1. Log into IFDB as a regular user.
1. Edit your profile.
1. Go down to section `5. Download Preferences`.
1. Open the `IF Archive Mirror` dropdown menu, select `ifarchive.smallwhitehouse.org (USA)` and `Save Changes`.
1. View the game [Anchorhead](https://ifdb.org/viewgame?id=op0uw1gn1tjqmjt7) and try to download `AnchorheadDemo.gblorb`.

## Observed behavior:
The download fails because it is trying to download from `ifarchive.smallwhitehouse.org` which doesn't exist any more as far as I can tell.

## Expected behavior:
There should not be a mirror dropdown menu. All traffic should be sent to `ifarchive.org`.

## Note:
This doesn't currently affect many of the download links because the functionality to change the links based on the `IF Archive Mirror` profile setting isn't functioning properly. See issue https://github.com/iftechfoundation/ifdb/issues/18 and https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/1 for more information. That's why I had to specifically pick the demo link for Anchorhead to demonstrate the problem.

**Comment by Durafen** [comment]
Mirrors are saved in `mirrors` sql table, delete the row there will eliminate it.

**Comment by erkyrath** [comment]
The whole mirrors system is out of date. `mirror.ifarchive.org` is no longer a random redirector; it's exactly the same as `www.ifarchive.org`. They're both handled by Cloudflare.

**Comment by erkyrath** [comment]
I guess the action here is "remove the mirrors dropdown and send all traffic to `ifarchive.org`."

**Comment by lkcampbell** [comment]
> I guess the action here is "remove the mirrors dropdown and send all traffic to `ifarchive.org`."

Edited Expected Behavior above to reflect this suggestion.

**Comment by lkcampbell** [comment]
Going to wait until https://github.com/iftechfoundation/ifdb/pull/67/files goes in because some of the mirror code ties into plugin code that is soon to be gone.

**Comment by lkcampbell** [comment]
Fixed by pull request https://github.com/iftechfoundation/ifdb/pull/99. Closing.
