### ISSUE TITLE
Problems with display of apostrophes and quotation marks in RSS feed

### ISSUE THREAD

**Issue by alice-blue** [iftechfoundation/ifdb#483]
[A piece of site news at the IFDB site](https://ifdb.org/news?item=131) looks like this. There are quotation marks around "Downloads" and "External Links" and an apostrophe in "doesn't."

![site news screenshot](https://github.com/iftechfoundation/ifdb/assets/12779726/acd0c2fe-374d-4dd5-a70a-ffe5ff9cf640)

On the RSS feed, it shows up like this, without the quotation marks or apostrophe:

![feedreader screenshot](https://github.com/iftechfoundation/ifdb/assets/12779726/fa4c0a17-c4e4-4360-82fb-087fe42d0454)

**Comment by dfabulich** [comment]
This is fixed now that we've switched to UTF-8.
