### ISSUE TITLE
Apostrophes are not appearing in description text in preview

### ISSUE THREAD

**Issue by alice-blue** [iftechfoundation/ifdb#488]
When someone [posted on intfiction.org](https://intfiction.org/t/not-yet-perished-an-if-about-the-war-in-ukraine/63620/4), linking to a game page on IFDB, the preview text did not include apostrophes where it should have. For example, the description below should say "We're on the road," not "Were." The actual IFDB page shows it correctly: https://ifdb.org/viewgame?history&id=jzizhav8dy828ct9

I'm not sure if this is an IFDB thing or an intfiction thing.

![preview card screenshot](https://github.com/iftechfoundation/ifdb/assets/12779726/6aeebdf5-4e5a-4166-a737-6644b8f22863)

**Comment by dfabulich** [comment]
This seems to have fixed itself now that we've switched to UTF-8.
