### ISSUE TITLE
Mojibake and broken queries for some non-ASCII characters in series and genre lists

### ISSUE THREAD

**Issue by jtn20** [iftechfoundation/ifdb#507]
(This is probably related to iftechfoundation/ifdb#508, but I wasn't 100% sure so I raised a new issue.)

The IFDB advanced search page https://ifdb.org/search has folds _Show all series names appearing in game listings_ and _Show all genres used in game listings_.

On expanding these folds, I see mojibake (wrong characters, indicating UTF-8 interpreted as ISO-8859-1) for some (but not all) items containing non-ASCII characters.

Examples of broken display / links:
* Genre _"acciÃ³"_ ([broken search link](https://ifdb.org/search?searchfor=genre:acci%c3%b3)): should be _acció_ ([manually corrected search link](https://ifdb.org/search?searchfor=genre:acci%f3), returns single game _[La fuga](https://ifdb.org/viewgame?id=saz1t56or902kqss)_)
* Series _"Aventuriers IntÃ©rimaires"_ ([broken search link](https://ifdb.org/search?searchfor=series:Aventuriers%20Int%c3%a9rimaires)): should be _Aventuriers Intérimaires_ ([manually corrected search link](https://ifdb.org/search?searchfor=series:Aventuriers%20Int%e9rimaires), returns single game _[Le kébab hanté](https://ifdb.org/viewgame?id=nmzjzrhbrhxsv3tx)_)
* (And about ten others. I spotted these series:
  * O Embuçado
  * Rêves Oniriques
  * Slacker Sláine.
  * Sort of a sequel to Strip Ém All
  * Serie Minúscula
  * Quêtes de Xhoromag
  * Dérive
  * Memòries d'un explorador)

but others are fine:
* Series _Кащей_ ([search link](https://ifdb.org/search?searchfor=series:%26%231050%3B%26%231072%3B%26%231097%3B%26%231077%3B%26%231081%3B)) successfuly returns a single game _[Кащей прячет смерть](https://ifdb.org/viewgame?id=p7b85itec9k3mcls)_
* Series _Dokidoki★Date_ ([search link](https://ifdb.org/search?searchfor=series:Dokidoki%26%239733%3BDate)) successfully returns a single game _[HSKY 회사설 미연시 챕터1](https://ifdb.org/viewgame?id=l4um1dkgyf5tksuq)_

Looking at [search](https://github.com/iftechfoundation/ifdb/blob/main/www/search) and browser developer tools, I see that the data for these comes from queries of the form
* https://ifdb.org/search?enum=series&xml
* https://ifdb.org/search?enum=genre&xml

Issuing these queries myself, I see:
* The HTTP headers contain `Content-Type: text/xml;charset=ISO-8859-1`. This charset looks wrong for the data. I don't know if anything takes any notice of it, but it should probably be fixed.
* The XML itself contains `<?xml version="1.0" encoding="UTF-8"?>`. This is an accurate description of the following XML data.
* Some characters (generally, western European ones) are included in the XML literally, encoded in UTF-8. These are the ones that end up showing mojibake / broken queries.
* More 'exotic' characters like Cyrillic are included in the XML as entities (e.g. `<item>&#1050;&#1072;&#1097;&#1077;&#1081;</item>`, `<item>Dokidoki&#9733;Date</item>`. These are the ones that end up unscathed.

I don't know the niceties of the Javascript's subsequent interpretation of this XML, but that suggests that emitting more characters as entities in XML, such that the XML is ASCII-only, would at the very least work around this problem.

(Incidentally, there is one genre name that's not the most lovely UTF-8: the work _[Coke Is It!](https://ifdb.org/viewgame?id=igcp4nw7md3ylwjs)_ has a genre that looks like _"Children's"_ but containing Unicode code point U+0092 ([manually constructed search link](https://ifdb.org/search?searchfor=genre:Children%92s)), which looks like it's intended to be a curly apostrophe in the Win1252 style, but is actually a control character. I was hoping this was crufty ancient data, but actually it was [only added in 2018](https://ifdb.org/viewgame?version=10&id=igcp4nw7md3ylwjs). Perhaps the best thing to do is to correct that game entry and hope no-one does it again.)

**Comment by dfabulich** [comment]
This seems to have been fixed by fixing #859

**Comment by dfabulich** [comment]
oops, I'm wrong. The links display properly, but the searches don't work

**Comment by dfabulich** [comment]
Fixed in #1004
