### ISSUE TITLE
viewgame links to some series or genre names containing non-ASCII characters don't work

### ISSUE THREAD

**Issue by jtn20** [iftechfoundation/ifdb#508]
There are two listings for "Cannelé & Nomnom" games: [beta](https://ifdb.org/viewgame?id=px4i00emsjwozza0) and [episode 1](https://ifdb.org/viewgame?id=i57zntqzl6fnkt5v).

They are marked as belonging to a series called _"Cannelé & Nomnom"_.

Clicking on the series link in either of the game pages produces (in Firefox) a _"No results were found"_ page, with the text field displaying _"series:CannelÃ© & Nomnom"_ (that's A-tilde and copyright-sign in place of the expected e-acute).

The search result link in the game page source is `/search?searchfor=series:Cannel%C3%A9+%26+Nomnom` (resolving to [this link](https://ifdb.org/search?searchfor=series:Cannel%C3%A9+%26+Nomnom) as an absolute URL). The %-encoded parts (C3 A9) represent the UTF-8 encoding of U+00E9 LATIN SMALL LETTER E WITH ACUTE. (But when interpreted as ISO-8859-1, they produce the Ã© mojibake seen above.)

If I hand-hack the URL to encode the ISO-8859-1 (latin1) representation of that character (i.e., `series:Cannel%E9+%26+Nomnom`) -- [link](https://ifdb.org/search?searchfor=series:Cannel%E9+%26+Nomnom) -- that works (returns both games from the series, sensible search box contents).

I don't know anything about IFDB's internal character representation (and I note open issue iftechfoundation/ifdb#859), but all the pages I've looked at (/viewgame, /editgame, search result) are served with HTTP header `Content-Type: text/html; charset=ISO-8859-1`, have the same in `<meta http-equiv>`, and contain literal `E9` bytes where "Cannelé" is mentioned. <s>So I guess it's generally Latin-1, and the series name in these games' data is fine, and whatever is transcoding the series name to UTF-8 for the series URL needs squashing.</s>

**Comment by dfabulich** [comment]
Unfortunately, this bug still persists, even though we've ported to UTF-8.
