### ISSUE TITLE
Clubs should be able to schedule events

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#552]
Clubs can currently declare "news," but the normal thing for a club to do is have a meeting/event, which is news-like, but isn't exactly news. In particular, club news items have only one date, the date that the news item was created, but an event announcement also needs to include the date of the event.

It should be possible to define a club event (a "meeting?") with a title, date (which is different from the date that the event was created/edited), description, and link.

Ideally it should also be possible to declare an event schedule, e.g. the SF Bay Area IF Meetup meets on the first Saturday of every month, so events don't have to be manually declared.

Finally, currently the "clubs" page sorts by date; it should sort by the date of the newest upcoming event or news item.

**Comment by salty-horse** [comment]
The clubs feature was removed
