### ISSUE TITLE
Review Dates Change Upon Editing

### ISSUE THREAD

**Issue by kaemiV** [iftechfoundation/ifdb#565]
When someone updates a review, even for the most minor thing, it changes the review date. Thus, a review can be dated years off or at this point even decades off of when it was actually posted. This is confusing and bad for the historicity of the site, because you can never actually be sure when a review was posted, and it messes with the review timeline, so you can't chart the ongoing community appraisal of the work.

A better solution would be for reviews to always display the date when they were originally posted, and then maybe a small notice at the bottom of the review can note "Review last updated on x."

**Comment by salty-horse** [comment]
I agree reviews should show their creation date instead of update date. (Including fetching and sorting by most recent, etc.)

Maybe show both dates only when viewing a specific review.

**Comment by salty-horse** [comment]
What's a compact way to add the update date?

I'm thinking of an "(edited)" text, and if you hover over it, there's a label with the date. Is that accessible enough?
