### ISSUE TITLE
Move “Links” up above “Member Reviews”

### ISSUE THREAD

**Issue by ahope1** [iftechfoundation/ifdb#566]
On mobile at least, the Links section on a game’s Details page is buried way down at the bottom of the page, below Member Reviews, where it’s easily missed and hard to get to. 

It would be better if the Links section were moved higher up the page so that it appears just after Tags and just before Member Reviews. Then, all the “bibliographic” info for the game would be neatly grouped together.

**Comment by dfabulich** [comment]
We removed the Links secstion
