### ISSUE TITLE
Replace all ifdb.tads.org with ifdb.org

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#7]
As we do the server transition, we'll want to ensure that we don't link to ifdb.tads.org.

I see a bunch of links to ifdb.tads.org in the database archive, and also in the code. (We especially don't want to link to ifdb.tads.org in emails we send out, e.g. new-user emails.)

**Comment by erkyrath** [comment]
Probably want this to be a config variable, so that `dev.ifdb.org` can run a completely separate test instance.

**Comment by dfabulich** [comment]
PR #17 addresses as much of this as we can in the code base, but we'll need to do a DB migration to replace ifdb.tads.org URLs in the DB with updated versions. (There are a _lot_ of those!)

**Comment by dfabulich** [comment]
I added a step to dev setup that handles the DB migration
