### ISSUE TITLE
Sql table clubs missing 2 columns

### ISSUE THREAD

**Issue by Durafen** [iftechfoundation/ifdb#8]
Accessing any club page results in error: 
```
The requested club is not in the database. It might have been deleted, or the link you followed to reach this page might be broken.
```
This happens because the query tries to access 2 columns (`password` and  `pswsalt`) that doesn't exist in the current sql dump.
In the current state, those 2 columns can added with empty data (it fixes the error).

**Comment by dfabulich** [comment]
Thanks! I constructed the `patch-schema.sql` script by hand, and I somehow missed these columns. I double checked it this time; I'm pretty sure I've got them all now.
