### ISSUE TITLE
Mark two tags as synonyms or merge two similar tags

### ISSUE THREAD

**Issue by qdacsvx** [iftechfoundation/ifdb#806]
Moderator (privileged user) options to perform tag clean-up. Moderators might run polls to sample user opinion about a: should a tag merge take place? b: what should the surviving tag be?

Currently tag voting isn't used. If users were informed how to vote for a tag (just add the tag you want to vote for yourself) users could vote on a game page where the two synonyms are present. Tag voting is a public anonymous poll - any logged in user can see the count of votes for each tag. The vote count is only shown if there are two or more votes.

Marking two tags as synonyms would mean they would match each other in (tag) searches. There should be a corresponding option to remove synonymity.

**Comment by dfabulich** [comment]
Moderators can now Bulk Add tags (Add tag X to games tagged Y), Bulk Delete tags, and Block tags in preference to a better synonym.
