### ISSUE TITLE
Use UTF-8

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#859]
IFDB stores all of its data in a MySQL `latin1` database and jumps through a bunch of hoops to prevent itself from getting accidentally transmogrified into UTF-8.

When I was porting from MySQL 5 to MariaDB 10, I accidentally restored the database as UTF-8, and so I began the process of trying to adopt UTF-8. I found it didn't seem to be _that_ much work to just use UTF-8. It was more a matter of deleting code than adding it, and making sure nothing got missed.

It would need a pretty serious test plan to make sure nothing got missed, but it seems doable to me.

**Comment by salty-horse** [comment]
If the codebase is prepared in advance to only work with utf-8, is it it just a matter of shutting down the website for a bit and converting the database?

**Comment by dfabulich** [comment]
While working on #995, I learned something that surprised me: **our database is in Windows-1252, not ISO-8859-1.**

[Windows-1252 is basically a superset of 8859-1.](https://stackoverflow.com/a/75789521/54829) There are a couple dozen characters that are defined as "control characters" in ISO-8859-1 and in UTF-8, but are defined as visible characters in 1252, and the smart apostrophe `\x92` is one of them.

`\x92` is all over our database, in reviews, etc. In ISO-8859-1 it's a non-renderable control character. It doesn't even display properly as an XML entity.
