### ISSUE TITLE
Frequency on tags page is not consistent with number of games in search results

### ISSUE THREAD

**Issue by alice-blue** [iftechfoundation/ifdb#882]
On the showtags page, one of the first tags says `cover art (1789)`

When you click on that "cover art" link, the first page of search results says "1-20 of 1643."
https://ifdb.org/search?searchfor=tag:cover+art

1789 vs. 1643.

I'm wondering if the frequency shown on the showtags page is not actually the number of games with that tag, but the number of times that tag has been given, including redundantly (i.e. if 6 people tagged "Lost Pig" with the "cover art" tag, is that counted as 6?).

If so, what should we do about that? We could fix the numbers on the showtags page to exclude redundant tags.

Or we could change the description on the showtags page to reflect that the number is not actually the number of games.

Or if, long-term, we're thinking of shifting the tag system to get rid of the concept of tag "owners" and allow only one occurrence of a tag per game, it might sort itself out? (I don't know if anyone has brought that up specifically, but if we're talking about having a per-game history of tagging, that would seem to be the format that would make sense with that, IMO.)

**Comment by dfabulich** [comment]
I think it should count games, not times, and, yes, in the long term, I think tags should stop having owners, and just be part of a game's history. #377
