### ISSUE TITLE
Adding a Reading Speed/Playthrough Time Spent Input on game pages

### ISSUE THREAD

**Issue by manonamora** [iftechfoundation/ifdb#919]
Game playtimes would be a super cool improvement on game pages, helping future players know what amount of time they should expect when playing a game (do they have time for a quick bite or do they need to sit down for multiple hours). 

This is a feature already available on the VNDB:
<img width="325" alt="image" src="https://github.com/user-attachments/assets/5425ad27-8f96-4928-a4c5-642f9a06f44b">

While authors can indicate the amount of time they expect a player will spend on their game (in the game description), it's not always a good indicator (some people read fast/slower, puzzle complexity depends on the player, etc...). Reviewers can also indicate a time spent in their reviews (text/tag), but it's just one person as well.

Letting anyone indicate how long it took them to play the game (especially users who don't write reviews/rate games) would be nice!
Either with a select/dropdown box with increments of 5/15mins or an input number box for a more specific input.

**Comment by jtn20** [comment]
I guess this is now addressed by PR #1018?
