### ISSUE TITLE
Use a CDN

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#926]
IFDB doesn't have a CDN, e.g. Cloudflare.

That would allow us to cache cover art, JS, and CSS at the edge, which can improve page-load performance, and protect us from DDOS attacks.

**Comment by salty-horse** [comment]
If JS and CSS are cached, it would be useful to move some code into it :) #914

**Comment by salty-horse** [comment]
Do CDNs support pre-resizing images? IFDB uses several different sizes.

**Comment by dfabulich** [comment]
The easy way is just to set cache headers on the resized images. Then the CDN will cache whatever images we generate.

But, yes, I think Cloudflare has a thing for this.

**Comment by dfabulich** [comment]
Now we use Cloudflare
