### ISSUE TITLE
Game update history can show wrong date for most recent entry

### ISSUE THREAD

**Issue by jtn20** [iftechfoundation/ifdb#940]
See for instance [this link to Curses](https://ifdb.org/viewgame?version=1&id=plvzam05bmz3enh8).

We're viewing an old revision of the page (v.1). In the "Page Update History" section, the date on the most recent revision (v.32 at the time of writing) is anachronistic: it says "29-Sep-2007 20:49". (I think for v.32 it should be "10-Sep-2024 17:00".) In general it seems to be the date of the currently viewed revision.

**Comment by salty-horse** [comment]
The code is incorrectly adding a new version to the top, and giving it the date/user of the requested entry (in this example, version 1).
