### ISSUE TITLE
Can't reset stylesheet to default

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb#957]
`https://ifdb.org/styles?set=default`

> An error occurred updating your profile - the style sheet selection has not been changed.

I can't seem to reproduce this locally (!) but it reproduces on prod and dev.

**Comment by dfabulich** [comment]
68b7f9d88579db11b4a3bff453f2b2d3965922c1 fixed it, but I don't really understand why.

**Comment by salty-horse** [comment]
Let's try `mysqli_execute_query` again after upgrading to PHP 8 #468

**Comment by salty-horse** [comment]
I tested, and it worked fine for me, so I committed it as part of b4ef2007bba38dcb1e7e4050f9c688c7076a5e37
